---
- name: Listen for events on a webhook
  hosts: all

  ## Define a webhook as source
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  ## Define rules with conditions and actions
  rules:
    - name: Event
      condition: event.payload.message == "fail"
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
