---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 7000

     ## Define the conditions we are looking for

  rules:
    - name: Event
      condition: event.payload.message == "fail"
      action:
        run_job_template:
          name: hello
          organization: "Default"
