---
- name: setup apache
  hosts: all
  become: true
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
